Import 3.4 packaging.

diff --git a/debian/PVER.postinst.in b/debian/PVER.postinst.in
--- a/debian/PVER.postinst.in
+++ b/debian/PVER.postinst.in
@@ -1,35 +1,18 @@
-#! /bin/sh -e
+#! /bin/sh
 
-if [ "$1" = configure ]; then
-    (
-    files=$(dpkg -L @PVER@ | sed -n '/^\/usr\/lib\/@PVER@\/.*\.py$/p')
-	@PVER@ /usr/lib/@PVER@/py_compile.py $files
-	if grep -sq '^byte-compile[^#]*optimize' /etc/python/debian_config; then
-	    @PVER@ -O /usr/lib/@PVER@/py_compile.py $files
-	fi
-    )
-fi
+set -e
 
 case "$1" in
-    configure|abort-upgrade|abort-remove|abort-deconfigure)
-
-        # Create empty directories in /usr/local
-        if [ ! -e /usr/local/lib/python@VER@ ]; then
-            mkdir -p /usr/local/lib/python@VER@ 2> /dev/null || true
-            chmod 2775 /usr/local/lib/python@VER@ 2> /dev/null || true
-            chown root:staff /usr/local/lib/python@VER@ 2> /dev/null || true
-        fi
-        if [ ! -e /usr/local/lib/python@VER@/site-packages ]; then
-            mkdir -p /usr/local/lib/python@VER@/site-packages 2> /dev/null || true
-            chmod 2775 /usr/local/lib/python@VER@/site-packages 2> /dev/null || true
-            chown root:staff /usr/local/lib/python@VER@/site-packages 2> /dev/null || true
-        fi
-    ;;
-
-    *)
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
+    configure)
+    files=$(dpkg -L lib@PVER@-stdlib | sed -n '/^\/usr\/lib\/@PVER@\/.*\.py$/p')
+    if [ -n "$files" ]; then
+	@PVER@ -E -S /usr/lib/@PVER@/py_compile.py $files
+	if grep -sq '^byte-compile[^#]*optimize' /etc/python/debian_config; then
+	    @PVER@ -E -S -O /usr/lib/@PVER@/py_compile.py $files
+	fi
+    else
+	echo >&2 "@PVER@: can't get files for byte-compilation"
+    fi
 esac
 
 #DEBHELPER#
